/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    competitions: Competition;
    problems: Problem;
    'problem-ratings': ProblemRating;
    'problem-edits': ProblemEdit;
    'ingestion-tokens': IngestionToken;
    'ingestion-jobs': IngestionJob;
    'ingestion-items': IngestionItem;
    'ingestion-assets': IngestionAsset;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    competitions: CompetitionsSelect<false> | CompetitionsSelect<true>;
    problems: ProblemsSelect<false> | ProblemsSelect<true>;
    'problem-ratings': ProblemRatingsSelect<false> | ProblemRatingsSelect<true>;
    'problem-edits': ProblemEditsSelect<false> | ProblemEditsSelect<true>;
    'ingestion-tokens': IngestionTokensSelect<false> | IngestionTokensSelect<true>;
    'ingestion-jobs': IngestionJobsSelect<false> | IngestionJobsSelect<true>;
    'ingestion-items': IngestionItemsSelect<false> | IngestionItemsSelect<true>;
    'ingestion-assets': IngestionAssetsSelect<false> | IngestionAssetsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  role: 'user' | 'editor' | 'admin';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "competitions".
 */
export interface Competition {
  id: number;
  /**
   * 全局唯一稳定标识，如 ipho-2026
   */
  slug: string;
  nameOriginal?: string | null;
  nameZh: string;
  nameEn: string;
  year: number;
  editionLabel?: string | null;
  level: 'national' | 'regional' | 'world';
  descriptionZh?: string | null;
  descriptionEn?: string | null;
  /**
   * 封面图（走 R2）
   */
  cover?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "problems".
 */
export interface Problem {
  id: number;
  /**
   * 全局唯一，如 ipho-2026-t1
   */
  slug: string;
  competition: number | Competition;
  /**
   * Stable paper code from ingestion, e.g. theory
   */
  paperCode?: string | null;
  /**
   * Problem number within the paper, e.g. T1
   */
  problemCode?: string | null;
  /**
   * 难度 1–5，见 content/difficulty-rubric.md
   */
  difficulty: number;
  /**
   * 知识点二级标签（多选），值域来自 content/tags-taxonomy.json
   */
  tags?:
    | (
        | 'kinematics'
        | 'newtonian-dynamics'
        | 'energy-momentum'
        | 'rigid-body'
        | 'oscillations-waves'
        | 'gravitation-orbits'
        | 'fluid-mechanics'
        | 'continuum-elasticity'
        | 'nonlinear-chaos'
        | 'electrostatics'
        | 'dc-current'
        | 'magnetostatics'
        | 'induction'
        | 'ac-transient'
        | 'magnetic-materials'
        | 'maxwell-em-waves'
        | 'thermodynamics-laws'
        | 'kinetic-theory'
        | 'statistical-physics'
        | 'phase-transitions'
        | 'heat-transfer'
        | 'geometric-optics'
        | 'wave-optics'
        | 'photometry-radiation'
        | 'modern-optics'
        | 'special-relativity'
        | 'general-relativity'
        | 'quantum-basics'
        | 'atomic-molecular'
        | 'nuclear-particle'
        | 'condensed-matter'
        | 'astrophysics-cosmology'
        | 'dimensional-analysis'
        | 'approximation-perturbation'
        | 'calculus-ode'
        | 'vectors-frames'
        | 'numerical-estimation'
        | 'data-analysis'
      )[]
    | null;
  /**
   * 题目原始语言 ISO 码，如 en / ru / de
   */
  originalLanguage: string;
  /**
   * 题干原始语言文本（LaTeX）
   */
  contentOriginal: string;
  /**
   * 中文题干（LaTeX），缺则留空
   */
  contentZh?: string | null;
  /**
   * 英文题干（LaTeX），缺则留空
   */
  contentEn?: string | null;
  answerOriginal?: string | null;
  answerZh?: string | null;
  answerEn?: string | null;
  /**
   * 出处，如 'IPhO 2026 Theory T1'
   */
  source: string;
  /**
   * Ingestion provenance page references
   */
  sourcePages?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Approved ingestion draft provenance
   */
  ingestionItem?: (number | null) | IngestionItem;
  /**
   * 官方解析链接，可选
   */
  officialSolutionUrl?: string | null;
  /**
   * 是否允许用户提交 Wiki 修改提案
   */
  allowWikiEdit?: boolean | null;
  status: 'draft' | 'pending' | 'published' | 'archived';
  totalLikes?: number | null;
  totalDislikes?: number | null;
  avgScore?: number | null;
  scoreCount?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ingestion-items".
 */
export interface IngestionItem {
  id: number;
  job: number | IngestionJob;
  identityKey: string;
  contentHash: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  fieldAssessments:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  validation:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  reviewState: 'needs-review' | 'reviewed' | 'rejected';
  revisionOf?: (number | null) | IngestionItem;
  createdProblem?: (number | null) | Problem;
  humanDiff?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  reviewedBy?: (number | null) | User;
  reviewedAt?: string | null;
  auditTrail:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ingestion-jobs".
 */
export interface IngestionJob {
  id: number;
  importId: string;
  idempotencyKey: string;
  actorToken: number | IngestionToken;
  status: 'needs-review' | 'reviewed' | 'rejected';
  competitionSlug: string;
  paperCode: string;
  problemCode: string;
  contentHash: string;
  sourceBundle:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  rawInput:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  normalizedInput:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  validation:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  revisionOf?: (number | null) | IngestionJob;
  createdProblem?: (number | null) | Problem;
  auditTrail:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  rejectReason?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ingestion-tokens".
 */
export interface IngestionToken {
  id: number;
  name: string;
  /**
   * SHA-256 hex digest only; never paste the raw token here.
   */
  tokenHash: string;
  scopes: ('ingestion:create' | 'ingestion:update' | 'ingestion:read-own')[];
  disabled: boolean;
  expiresAt?: string | null;
  lastUsedAt?: string | null;
  rotatedFrom?: (number | null) | IngestionToken;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "problem-ratings".
 */
export interface ProblemRating {
  id: number;
  problem: number | Problem;
  user: number | User;
  /**
   * -1 踩 / 0 无 / 1 赞
   */
  vote: number;
  /**
   * 1–5 星，可空
   */
  score?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "problem-edits".
 */
export interface ProblemEdit {
  id: number;
  targetProblem: number | Problem;
  submitUser: number | User;
  editType: 'content' | 'answer' | 'formula' | 'supplement';
  editMultiContent?: {
    contentOriginal?: string | null;
    contentZh?: string | null;
    contentEn?: string | null;
    answerOriginal?: string | null;
    answerZh?: string | null;
    answerEn?: string | null;
  };
  /**
   * 修改说明
   */
  remark?: string | null;
  status: 'pending' | 'approved' | 'rejected';
  /**
   * 审核通过时记录的原题快照
   */
  beforeSnapshot?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * 审核通过时记录的新内容快照
   */
  afterSnapshot?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  reviewedBy?: (number | null) | User;
  reviewedAt?: string | null;
  /**
   * 驳回理由（驳回时必填）
   */
  rejectReason?: string | null;
  /**
   * 关联的题目版本号（审计）
   */
  targetVersion?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ingestion-assets".
 */
export interface IngestionAsset {
  id: number;
  item: number | IngestionItem;
  assetKey: string;
  metadata:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  r2ObjectKey?: string | null;
  contentHash?: string | null;
  mediaType?: string | null;
  originalFileName?: string | null;
  byteSize?: number | null;
  status: 'unreviewed' | 'approved' | 'rejected';
  createdMedia?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'competitions';
        value: number | Competition;
      } | null)
    | ({
        relationTo: 'problems';
        value: number | Problem;
      } | null)
    | ({
        relationTo: 'problem-ratings';
        value: number | ProblemRating;
      } | null)
    | ({
        relationTo: 'problem-edits';
        value: number | ProblemEdit;
      } | null)
    | ({
        relationTo: 'ingestion-tokens';
        value: number | IngestionToken;
      } | null)
    | ({
        relationTo: 'ingestion-jobs';
        value: number | IngestionJob;
      } | null)
    | ({
        relationTo: 'ingestion-items';
        value: number | IngestionItem;
      } | null)
    | ({
        relationTo: 'ingestion-assets';
        value: number | IngestionAsset;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "competitions_select".
 */
export interface CompetitionsSelect<T extends boolean = true> {
  slug?: T;
  nameOriginal?: T;
  nameZh?: T;
  nameEn?: T;
  year?: T;
  editionLabel?: T;
  level?: T;
  descriptionZh?: T;
  descriptionEn?: T;
  cover?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "problems_select".
 */
export interface ProblemsSelect<T extends boolean = true> {
  slug?: T;
  competition?: T;
  paperCode?: T;
  problemCode?: T;
  difficulty?: T;
  tags?: T;
  originalLanguage?: T;
  contentOriginal?: T;
  contentZh?: T;
  contentEn?: T;
  answerOriginal?: T;
  answerZh?: T;
  answerEn?: T;
  source?: T;
  sourcePages?: T;
  ingestionItem?: T;
  officialSolutionUrl?: T;
  allowWikiEdit?: T;
  status?: T;
  totalLikes?: T;
  totalDislikes?: T;
  avgScore?: T;
  scoreCount?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "problem-ratings_select".
 */
export interface ProblemRatingsSelect<T extends boolean = true> {
  problem?: T;
  user?: T;
  vote?: T;
  score?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "problem-edits_select".
 */
export interface ProblemEditsSelect<T extends boolean = true> {
  targetProblem?: T;
  submitUser?: T;
  editType?: T;
  editMultiContent?:
    | T
    | {
        contentOriginal?: T;
        contentZh?: T;
        contentEn?: T;
        answerOriginal?: T;
        answerZh?: T;
        answerEn?: T;
      };
  remark?: T;
  status?: T;
  beforeSnapshot?: T;
  afterSnapshot?: T;
  reviewedBy?: T;
  reviewedAt?: T;
  rejectReason?: T;
  targetVersion?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ingestion-tokens_select".
 */
export interface IngestionTokensSelect<T extends boolean = true> {
  name?: T;
  tokenHash?: T;
  scopes?: T;
  disabled?: T;
  expiresAt?: T;
  lastUsedAt?: T;
  rotatedFrom?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ingestion-jobs_select".
 */
export interface IngestionJobsSelect<T extends boolean = true> {
  importId?: T;
  idempotencyKey?: T;
  actorToken?: T;
  status?: T;
  competitionSlug?: T;
  paperCode?: T;
  problemCode?: T;
  contentHash?: T;
  sourceBundle?: T;
  rawInput?: T;
  normalizedInput?: T;
  validation?: T;
  revisionOf?: T;
  createdProblem?: T;
  auditTrail?: T;
  rejectReason?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ingestion-items_select".
 */
export interface IngestionItemsSelect<T extends boolean = true> {
  job?: T;
  identityKey?: T;
  contentHash?: T;
  data?: T;
  fieldAssessments?: T;
  validation?: T;
  reviewState?: T;
  revisionOf?: T;
  createdProblem?: T;
  humanDiff?: T;
  reviewedBy?: T;
  reviewedAt?: T;
  auditTrail?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ingestion-assets_select".
 */
export interface IngestionAssetsSelect<T extends boolean = true> {
  item?: T;
  assetKey?: T;
  metadata?: T;
  r2ObjectKey?: T;
  contentHash?: T;
  mediaType?: T;
  originalFileName?: T;
  byteSize?: T;
  status?: T;
  createdMedia?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}